# Site settings
title: Mohamed Zaatar Blog
description: 'A Readify developer/consultant. Passionate about Software development, IT and cars. This blog for my technical and personal views.'
url: 'http://mzaatar.github.io/'
baseurl: 'http://mzaatar.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mohamed Zaatar'
  email: mzaatar@outlook.com.au
  twitter_username: mzaatar
  #facebook_username: joshgerdes
  github_username:  mzaatar
  linkedin_username:  mzaatar

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

theme: jekyll-theme-slate
